
services:

  backend:
    build:
      context: ./backend
    container_name: inv_dc_backend
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8060:8000"
    env_file:
      - ./backend/.env.dev
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.base
      PYTHONPATH: /app
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      app_net:
        aliases:
          - backend
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build:
      context: ../flet_inventario
    container_name: inv_dc_frontend
    volumes:
      - ../flet_inventario:/app
    ports:
      - "127.0.0.1:8061:8080"
    env_file:
      - ../flet_inventario/.env
    environment:
      API_BASE_URL: http://backend:8000/api
    networks:
      app_net:
        aliases:
          - frontend
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: inv_dc_mongo
    restart: always
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      app_net:
        aliases:
          - mongo
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

networks:
  app_net:
    name: inventarios_datacom_net
